<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>ProjetoDC</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Data\Itens\meat.json" />
    <Content Include="Data\Itens\medicine.json" />
    <Content Include="Data\Itens\gabumon_horn.json" />
    <Content Include="Data\NPCs\npc_exemplo.json" />
    <Content Include="Data\NPCs\npc_gaogamon.json" />
    <Content Include="Data\NPCs\npc_togemon.json" />
    <Content Include="Data\NPCs\npc_impmon.json" />
    <Content Include="Data\NPCs\npc_palmon.json" />
    <Content Include="Data\NPCs\npc_tortamon.json" />
    <Content Include="Data\Quests\quest_exemplo.json" />
    <Content Include="Data\Quests\quest_prove_ataque.json" />
    <Content Include="Data\Quests\quest_prove_defesa.json" />
    <Content Include="Data\Quests\quest_chifres.json" />
    <Content Include="Data\Quests\quest_trilha_palmon.json" />
    <Content Include="Data\Maps\floresta_inicial.json" />
    <Content Include="Data\Tournaments\copa_novato.json" />
    <Content Include="Data\Tournaments\torneio_rookie.json" />
    <Content Include="Data\Tournaments\desafio_champion.json" />
    <Content Include="Data\Tournaments\trio_das_trevas.json" />
    <Content Include="Data\Tournaments\trio_tamers.json" />
    <Content Include="Data\Tournaments\copa_ultimate.json" />
    <Content Include="Data\Tournaments\reis_do_mar.json" />
    <Content Include="Data\Tournaments\copa_mega.json" />
    <Content Include="Data\Tournaments\trio_celestial.json" />
    <Content Include="Data\Tournaments\trio_guardiao_02.json" />
    <Content Include="Data\Tournaments\copa_lendaria.json" />
    <Content Include="Data\Tournaments\copa_mega_revanche.json" />
    <Content Include="Data\Digimon\yaamon.json" />
    <Content Include="Data\Digimon\wanyamon.json" />
    <Content Include="Data\Digimon\tanemon.json" />
    <Content Include="Data\Digimon\viximon.json" />
    <Content Include="Data\Digimon\gummymon.json" />
    <Content Include="Data\Digimon\gigimon.json" />
    <Content Include="Data\Digimon\motimon.json" />
    <Content Include="Data\Digimon\tokomon.json" />
    <Content Include="Data\Digimon\tsunomon.json" />
    <Content Include="Data\Digimon\koromon.json" />
    <Content Include="Data\Digimon\keemon.json" />
    <Content Include="Data\Digimon\yuramon.json" />
    <Content Include="Data\Digimon\punimon.json" />
    <Content Include="Data\Digimon\botamon.json" />
    <Content Include="Data\Digimon\gaogamon.json" />
    <Content Include="Data\Digimon\geogreymon.json" />
    <Content Include="Data\Digimon\garurumon.json" />
    <Content Include="Data\Digimon\greymon.json" />
    <Content Include="Data\Digimon\gaomon.json" />
    <Content Include="Data\Digimon\growlmon.json" />
    <Content Include="Data\Digimon\sunflowmon.json" />
    <Content Include="Data\Digimon\wizardmon.json" />
    <Content Include="Data\Digimon\impmon.json" />
    <Content Include="Data\Digimon\lalamon.json" />
    <Content Include="Data\Digimon\angemon.json" />
    <Content Include="Data\Digimon\gargomon.json" />
    <Content Include="Data\Digimon\kyubimon.json" />
    <Content Include="Data\Digimon\togemon.json" />
    <Content Include="Data\Digimon\renamon.json" />
    <Content Include="Data\Digimon\agumon_savers.json" />
    <Content Include="Data\Digimon\kabuterimon.json" />
    <Content Include="Data\Digimon\terriermon.json" />
    <Content Include="Data\Digimon\guilmon.json" />
    <Content Include="Data\Digimon\palmon.json" />
    <Content Include="Data\Digimon\patamon.json" />
    <Content Include="Data\Digimon\tentomon.json" />
    <Content Include="Data\Digimon\gabumon.json" />
    <Content Include="Data\Digimon\agumon.json" />
    <Content Include="Data\Digimon\metalgreymon.json" />
    <Content Include="Data\Digimon\weregarurumon.json" />
    <Content Include="Data\Digimon\wargrowlmon.json" />
    <Content Include="Data\Digimon\rapidmon.json" />
    <Content Include="Data\Digimon\magnaangemon.json" />
    <Content Include="Data\Digimon\geogreymon_savers.json" />
    <Content Include="Data\Digimon\devimon.json" />
    <Content Include="Data\Digimon\icedevimon.json" />
    <Content Include="Data\Digimon\devidramon.json" />
    <Content Include="Data\Digimon\machgaogamon.json" />
    <Content Include="Data\Digimon\taomon.json" />
    <Content Include="Data\Digimon\lillymon.json" />
    <Content Include="Data\Digimon\megakabuterimon.json" />
    <Content Include="Data\Digimon\wargreymon.json" />
    <Content Include="Data\Digimon\metalgarurumon.json" />
    <Content Include="Data\Digimon\gallantmon.json" />
    <Content Include="Data\Digimon\megagargomon.json" />
    <Content Include="Data\Digimon\seraphimon.json" />
    <Content Include="Data\Digimon\poyomon.json" />
    <Content Include="Data\Digimon\yokomon.json" />
    <Content Include="Data\Digimon\biyomon.json" />
    <Content Include="Data\Digimon\birdramon.json" />
    <Content Include="Data\Digimon\garudamon.json" />
    <Content Include="Data\Digimon\hououmon.json" />
    <Content Include="Data\Digimon\pichimon.json" />
    <Content Include="Data\Digimon\bukamon.json" />
    <Content Include="Data\Digimon\gomamon.json" />
    <Content Include="Data\Digimon\ikkakumon.json" />
    <Content Include="Data\Digimon\zudomon.json" />
    <Content Include="Data\Digimon\vikemon.json" />
    <Content Include="Data\Digimon\nyaromon.json" />
    <Content Include="Data\Digimon\salamon.json" />
    <Content Include="Data\Digimon\gatomon.json" />
    <Content Include="Data\Digimon\angewomon.json" />
    <Content Include="Data\Digimon\magnadramon.json" />
    <Content Include="Data\Digimon\herculeskabuterimon.json" />
    <Content Include="Data\Digimon\rosemon.json" />
    <Content Include="Data\Digimon\yolkmon.json" />
    <Content Include="Data\Digimon\fluffymon.json" />
    <Content Include="Data\Digimon\pteromon.json" />
    <Content Include="Data\Digimon\galemon.json" />
    <Content Include="Data\Digimon\grandgalemon.json" />
    <Content Include="Data\Digimon\zephagamon.json" />
    <Content Include="Data\Digimon\pinochimon.json" />
    <Content Include="Data\Digimon\jyarimon.json" />
    <Content Include="Data\Digimon\elizamon.json" />
    <Content Include="Data\Digimon\dimetromon.json" />
    <Content Include="Data\Digimon\lamiamon.json" />
    <Content Include="Data\Digimon\medusamon.json" />
    <Content Include="Data\Digimon\leviamon.json" />
    <Content Include="Data\Digimon\lucemon_satan.json" />
    <Content Include="Data\Digimon\lucemon.json" />
    <Content Include="Data\Digimon\lucemon_falldown.json" />
    <Content Include="Data\Digimon\barbamon.json" />
    <Content Include="Data\Digimon\belphemon_rage.json" />
    <Content Include="Data\Digimon\belphemon.json" />
    <Content Include="Data\Digimon\kudamon.json" />
    <Content Include="Data\Digimon\reppamon.json" />
    <Content Include="Data\Digimon\chirinmon.json" />
    <Content Include="Data\Digimon\dracomon.json" />
    <Content Include="Data\Digimon\coredramon_green.json" />
    <Content Include="Data\Digimon\groundramon.json" />
    <Content Include="Data\Digimon\breakdramon.json" />
    <Content Include="Data\Digimon\coredramon_blue.json" />
    <Content Include="Data\Digimon\wingdramon.json" />
    <Content Include="Data\Digimon\slayerdramon.json" />
    <Content Include="Data\Digimon\veemon.json" />
    <Content Include="Data\Digimon\veedramon.json" />
    <Content Include="Data\Digimon\aeroveedramon.json" />
    <Content Include="Data\Digimon\ulforceveedramon.json" />
    <Content Include="Data\Digimon\magnamon.json" />
    <Content Include="Data\Digimon\kentaurusmon.json" />
    <Content Include="Data\Digimon\kotemon.json" />
    <Content Include="Data\Digimon\gladimon.json" />
    <Content Include="Data\Digimon\knightmon.json" />
    <Content Include="Data\Digimon\crusadermon.json" />
    <Content Include="Data\Digimon\dorumon.json" />
    <Content Include="Data\Digimon\dorugamon.json" />
    <Content Include="Data\Digimon\dorugreymon.json" />
    <Content Include="Data\Digimon\alphamon.json" />
    <Content Include="Data\Digimon\raptordramon.json" />
    <Content Include="Data\Digimon\grademon.json" />
    <Content Include="Data\Digimon\dorugoramon.json" />
    <Content Include="Data\Digimon\dexdorugamon.json" />
    <Content Include="Data\Digimon\dexdorugreymon.json" />
    <Content Include="Data\Digimon\dexdorugoramon.json" />
    <Content Include="Data\Digimon\craniummon.json" />
    <Content Include="Data\Digimon\dynasmon.json" />
    <Content Include="Data\Digimon\duftmon.json" />
    <Content Include="Data\Digimon\gankoomon.json" />
    <Content Include="Data\Digimon\hackmon.json" />
    <Content Include="Data\Digimon\baohackmon.json" />
    <Content Include="Data\Digimon\saviorhackmon.json" />
    <Content Include="Data\Digimon\jesmon.json" />
    <Content Include="Data\Digimon\phascomon.json" />
    <Content Include="Data\Digimon\astamon.json" />
    <Content Include="Data\Digimon\pafumon.json" />
    <Content Include="Data\Digimon\kyaromon.json" />
    <Content Include="Data\Digimon\shoemon.json" />
    <Content Include="Data\Digimon\shoeshoemon.json" />
    <Content Include="Data\Digimon\chaperomon.json" />
    <Content Include="Data\Digimon\cendrillmon.json" />
    <Content Include="Data\Digimon\lilithmon.json" />
    <Content Include="Data\Digimon\muchomon.json" />
    <Content Include="Data\Digimon\cockatrimon.json" />
    <Content Include="Data\Digimon\delumon.json" />
    <Content Include="Data\Digimon\medievaldukemon.json" />
    <Content Include="Data\Digimon\mokumon.json" />
    <Content Include="Data\Digimon\petimeramon.json" />
    <Content Include="Data\Digimon\ghostmon.json" />
    <Content Include="Data\Digimon\bakemon.json" />
    <Content Include="Data\Digimon\fantomon.json" />
    <Content Include="Data\Digimon\demon.json" />
    <Content Include="Data\Digimon\beelzebumon.json" />
    <Content Include="Data\Digimon\sunamon.json" />
    <Content Include="Data\Digimon\goromon.json" />
    <Content Include="Data\Digimon\sunarizamon.json" />
    <Content Include="Data\Digimon\tortamon.json" />
    <Content Include="Data\Digimon\triceramon.json" />
    <Content Include="Data\Digimon\ancientsphinxmon.json" />
    <Content Include="Data\Digimon\boltmon.json" />
    <Content Include="Data\Digimon\kuramon.json" />
    <Content Include="Data\Digimon\tsumemon.json" />
    <Content Include="Data\Digimon\bemmon.json" />
    <Content Include="Data\Digimon\snatchmon.json" />
    <Content Include="Data\Digimon\destromon.json" />
    <Content Include="Data\Digimon\ragnamon.json" />
    <Content Include="Data\Digimon\dinomon.json" />
    <Content Include="Data\Evolutions\motimon_evolutions.json" />
    <Content Include="Data\Evolutions\tokomon_evolutions.json" />
    <Content Include="Data\Evolutions\gigimon_evolutions.json" />
    <Content Include="Data\Evolutions\tsunomon_evolutions.json" />
    <Content Include="Data\Evolutions\koromon_evolutions.json" />
    <Content Include="Data\Evolutions\keemon_evolutions.json" />
    <Content Include="Data\Evolutions\yuramon_evolutions.json" />
    <Content Include="Data\Evolutions\punimon_evolutions.json" />
    <Content Include="Data\Evolutions\botamon_evolutions.json" />
    <Content Include="Data\Evolutions\agumon_evolutions.json" />
    <Content Include="Data\Evolutions\gabumon_evolutions.json" />
    <Content Include="Data\Evolutions\tentomon_evolutions.json" />
    <Content Include="Data\Evolutions\patamon_evolutions.json" />
    <Content Include="Data\Evolutions\gaomon_evolutions.json" />
    <Content Include="Data\Evolutions\palmon_evolutions.json" />
    <Content Include="Data\Evolutions\guilmon_evolutions.json" />
    <Content Include="Data\Evolutions\terriermon_evolutions.json" />
    <Content Include="Data\Evolutions\renamon_evolutions.json" />
    <Content Include="Data\Evolutions\impmon_evolutions.json" />
    <Content Include="Data\Evolutions\lalamon_evolutions.json" />
    <Content Include="Data\Evolutions\gummymon_evolutions.json" />
    <Content Include="Data\Evolutions\viximon_evolutions.json" />
    <Content Include="Data\Evolutions\wanyamon_evolutions.json" />
    <Content Include="Data\Evolutions\yaamon_evolutions.json" />
    <Content Include="Data\Evolutions\tanemon_evolutions.json" />
    <Content Include="Data\Evolutions\agumon_savers_evolutions.json" />
    <Content Include="Data\Evolutions\greymon_evolutions.json" />
    <Content Include="Data\Evolutions\garurumon_evolutions.json" />
    <Content Include="Data\Evolutions\growlmon_evolutions.json" />
    <Content Include="Data\Evolutions\gargomon_evolutions.json" />
    <Content Include="Data\Evolutions\angemon_evolutions.json" />
    <Content Include="Data\Evolutions\gaogamon_evolutions.json" />
    <Content Include="Data\Evolutions\kyubimon_evolutions.json" />
    <Content Include="Data\Evolutions\togemon_evolutions.json" />
    <Content Include="Data\Evolutions\kabuterimon_evolutions.json" />
    <Content Include="Data\Evolutions\metalgreymon_evolutions.json" />
    <Content Include="Data\Evolutions\weregarurumon_evolutions.json" />
    <Content Include="Data\Evolutions\wargrowlmon_evolutions.json" />
    <Content Include="Data\Evolutions\rapidmon_evolutions.json" />
    <Content Include="Data\Evolutions\magnaangemon_evolutions.json" />
    <Content Include="Data\Evolutions\poyomon_evolutions.json" />
    <Content Include="Data\Evolutions\yokomon_evolutions.json" />
    <Content Include="Data\Evolutions\biyomon_evolutions.json" />
    <Content Include="Data\Evolutions\birdramon_evolutions.json" />
    <Content Include="Data\Evolutions\garudamon_evolutions.json" />
    <Content Include="Data\Evolutions\pichimon_evolutions.json" />
    <Content Include="Data\Evolutions\bukamon_evolutions.json" />
    <Content Include="Data\Evolutions\gomamon_evolutions.json" />
    <Content Include="Data\Evolutions\ikkakumon_evolutions.json" />
    <Content Include="Data\Evolutions\zudomon_evolutions.json" />
    <Content Include="Data\Evolutions\nyaromon_evolutions.json" />
    <Content Include="Data\Evolutions\salamon_evolutions.json" />
    <Content Include="Data\Evolutions\gatomon_evolutions.json" />
    <Content Include="Data\Evolutions\angewomon_evolutions.json" />
    <Content Include="Data\Evolutions\megakabuterimon_evolutions.json" />
    <Content Include="Data\Evolutions\lillymon_evolutions.json" />
    <Content Include="Data\Evolutions\yolkmon_evolutions.json" />
    <Content Include="Data\Evolutions\fluffymon_evolutions.json" />
    <Content Include="Data\Evolutions\pteromon_evolutions.json" />
    <Content Include="Data\Evolutions\galemon_evolutions.json" />
    <Content Include="Data\Evolutions\grandgalemon_evolutions.json" />
    <Content Include="Data\Evolutions\jyarimon_evolutions.json" />
    <Content Include="Data\Evolutions\elizamon_evolutions.json" />
    <Content Include="Data\Evolutions\dimetromon_evolutions.json" />
    <Content Include="Data\Evolutions\lamiamon_evolutions.json" />
    <Content Include="Data\Evolutions\pafumon_evolutions.json" />
    <Content Include="Data\Evolutions\kyaromon_evolutions.json" />
    <Content Include="Data\Evolutions\shoemon_evolutions.json" />
    <Content Include="Data\Evolutions\shoeshoemon_evolutions.json" />
    <Content Include="Data\Evolutions\chaperomon_evolutions.json" />
    <Content Include="Data\Evolutions\muchomon_evolutions.json" />
    <Content Include="Data\Evolutions\cockatrimon_evolutions.json" />
    <Content Include="Data\Evolutions\delumon_evolutions.json" />
    <Content Include="Data\Evolutions\mokumon_evolutions.json" />
    <Content Include="Data\Evolutions\petimeramon_evolutions.json" />
    <Content Include="Data\Evolutions\ghostmon_evolutions.json" />
    <Content Include="Data\Evolutions\bakemon_evolutions.json" />
    <Content Include="Data\Evolutions\fantomon_evolutions.json" />
    <Content Include="Data\Evolutions\sunamon_evolutions.json" />
    <Content Include="Data\Evolutions\goromon_evolutions.json" />
    <Content Include="Data\Evolutions\sunarizamon_evolutions.json" />
    <Content Include="Data\Evolutions\tortamon_evolutions.json" />
    <Content Include="Data\Evolutions\triceramon_evolutions.json" />
    <Content Include="Data\Evolutions\kuramon_evolutions.json" />
    <Content Include="Data\Evolutions\tsumemon_evolutions.json" />
    <Content Include="Data\Evolutions\bemmon_evolutions.json" />
    <Content Include="Data\Evolutions\snatchmon_evolutions.json" />
    <Content Include="Data\Evolutions\destromon_evolutions.json" />
    <Content Include="Data\Evolutions\lucemon_evolutions.json" />
    <Content Include="Data\Evolutions\lucemon_falldown_evolutions.json" />
    <Content Include="Data\Evolutions\phascomon_evolutions.json" />
    <Content Include="Data\Evolutions\astamon_evolutions.json" />
    <Content Include="Data\Evolutions\kudamon_evolutions.json" />
    <Content Include="Data\Evolutions\reppamon_evolutions.json" />
    <Content Include="Data\Evolutions\chirinmon_evolutions.json" />
    <Content Include="Data\Evolutions\dracomon_evolutions.json" />
    <Content Include="Data\Evolutions\coredramon_green_evolutions.json" />
    <Content Include="Data\Evolutions\groundramon_evolutions.json" />
    <Content Include="Data\Evolutions\coredramon_blue_evolutions.json" />
    <Content Include="Data\Evolutions\wingdramon_evolutions.json" />
    <Content Include="Data\Evolutions\veemon_evolutions.json" />
    <Content Include="Data\Evolutions\veedramon_evolutions.json" />
    <Content Include="Data\Evolutions\aeroveedramon_evolutions.json" />
    <Content Include="Data\Evolutions\kotemon_evolutions.json" />
    <Content Include="Data\Evolutions\gladimon_evolutions.json" />
    <Content Include="Data\Evolutions\knightmon_evolutions.json" />
    <Content Include="Data\Evolutions\dorumon_evolutions.json" />
    <Content Include="Data\Evolutions\dorugamon_evolutions.json" />
    <Content Include="Data\Evolutions\dorugreymon_evolutions.json" />
    <Content Include="Data\Evolutions\raptordramon_evolutions.json" />
    <Content Include="Data\Evolutions\grademon_evolutions.json" />
    <Content Include="Data\Evolutions\dexdorugamon_evolutions.json" />
    <Content Include="Data\Evolutions\dexdorugreymon_evolutions.json" />
    <Content Include="Data\Evolutions\hackmon_evolutions.json" />
    <Content Include="Data\Evolutions\baohackmon_evolutions.json" />
    <Content Include="Data\Evolutions\saviorhackmon_evolutions.json" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\Audio\SFX\" />
    <Folder Include="Assets\Audio\Music\" />
    <Folder Include="Assets\Fonts\" />
    <Folder Include="Assets\Sprites\Digimon\" />
    <Folder Include="Assets\Themes\" />
    <Folder Include="Data\Passives\" />
    <Folder Include="Data\Roles\" />
    <Folder Include="Data\Maps\" />
    <Folder Include="Data\Itens\" />
    <Folder Include="Data\Training\" />
    <Folder Include="Data\Buildings\" />
    <Folder Include="Data\NPCs\" />
    <Folder Include="Data\Quests\" />
    <Folder Include="Data\Tournaments\" />
    <Folder Include="Data\Eggs\" />
    <Folder Include="Scenes\Battle\" />
    <Folder Include="Scenes\Exploration\" />
    <Folder Include="Scenes\Digimon\" />
    <Folder Include="Scenes\Tournament\" />
    <Folder Include="Scenes\Training\" />
    <Folder Include="Scenes\UI\" />
    <Folder Include="Scenes\Main\" />
    <Folder Include="Saves\" />
    <Folder Include="Scripts\Systems\Battle\Animations\" />
    <Folder Include="Scripts\Utils\" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
    <None Include="AGENTS.md" />
    <None Include="CLAUDE.md" />
  </ItemGroup>
</Project>